apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: broker
        resources:
          limits:
            memory: 2000Mi
