apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: zookeeper
        resources:
          limits:
            memory: 1200Mi